### ISSUE TITLE
There are some issues with the divide section

### ISSUE THREAD

**Issue by fourfireM** [DreamMr/HR-Bench#1]
If x is related to the width of the image, then the columns in the 2D array should represent the change in width and not the rows

``` # divide
  direction = [[0,0],[0,1],[1,0],[1,1]] # top left, top right, bottom left, bottom right
  dir_loc = ['top left','top right','bottom left','bottom right']
  sub_react = {}
  loc_dic = {}
  for loc,dir in zip(dir_loc,direction):
      #the orginal code is
      #    new_x = x + dir[0] * split_w
      #    new_y = y + dir[1] * split_h      
      #    global_new_x = global_rect[0] + dir[0] * split_w
      #    global_new_y = global_rect[1] + dir[1] * split_h

      new_x = x + dir[1] * split_w
      new_y = y + dir[0] * split_h
      
      global_new_x = global_rect[1] + dir[1] * split_w
      global_new_y = global_rect[0] + dir[0] * split_h
      
      if new_x < 0 or new_y < 0 or new_x >= total_w or new_y >= total_h:
          continue
      
      loc_dic[loc] = {'global_react':[global_new_x,global_new_y,split_h,split_w],'local_react':[new_x,new_y,split_h,split_w]}
  ```
So the divide section should be changed so that, assuming 7680, 4992 images are passed in, the output should be
```
{'top left': {'global_react': [0, 0, 3840, 2496], 'local_react': [0, 0, 3840, 2496]}, 'top right': {'global_react': [2496, 0, 3840, 2496], 'local_react': [2496, 0, 3840, 2496]}, 'bottom left': {'global_react': [0, 3840, 3840, 2496], 'local_react': [0, 3840, 3840, 2496]}, 'bottom right': {'global_react': [2496, 3840, 3840, 2496], 'local_react': [2496, 3840, 3840, 2496]}}
```

**Comment by DreamMr** [comment]
Thank you for your attention to our work.

After carefully reviewing the matter, we confirm that your observation is correct: x represents the width of the image, and y represents the height. In the divide code, there is indeed a mismatch between the directional descriptions and the coordiante calculations. However, since the subsequent processes do not rely on these directional descriptions, this discrepancy does not affect the final results.

We have carefully reviewed the code you provided, and it indeed resolves this issue. However, we noticed that in your code, when calculating global_new_x and global_new_y, you use the global_react[1] and global_react[0] from the previous layer (misalignment). This would be result in the split images not meeting the original logic in terms of size and coordinates.
e.g., height: 7680, width: 4992 image
Correct output:
`{'top left': {'global_react': [2496, 0, 1920, 1248], 'local_react': [0, 0, 1920, 1248]}, 'bottom left': {'global_react': [2496, 1920, 1920, 1248], 'local_react': [0, 1920, 1920, 1248]}, 'top right': {'global_react': [3744, 0, 1920, 1248], 'local_react': [1248, 0, 1920, 1248]}, 'bottom right': {'global_react': [3744, 1920, 1920, 1248], 'local_react': [1248, 1920, 1920, 1248]}}`
Your code output:
`{'top left': {'global_react': [3840, 0, 1920, 1248], 'local_react': [0, 0, 1920, 1248]}, 'bottom left': {'global_react': [5088, 0, 1920, 1248], 'local_react': [1248, 0, 1920, 1248]}, 'top right': {'global_react': [3840, 1920, 1920, 1248], 'local_react': [0, 1920, 1920, 1248]}, 'bottom right': {'global_react': [5088, 1920, 1920, 1248], 'local_react': [1248, 1920, 1920, 1248]}}`

To address the issue, we have corrected our original code by swapping the directional text descriptions to align with the coordinate calculations. This adjustment ensures consistency while preserving the integrity of subsequent processes.
``` 
direction = [[0,0],[0,1],[1,0],[1,1]] # top left, bottom left, top right, bottom right
dir_loc = ['top left','bottom left','top right','bottom right']
sub_react = {}
loc_dic = {}
for loc,dir in zip(dir_loc,direction):
    new_x = x + dir[0] * split_w
    new_y = y + dir[1] * split_h
    global_new_x = global_rect[0] + dir[0] * split_w
    global_new_y = global_rect[1] + dir[1] * split_h

    if new_x < 0 or new_y < 0 or new_x >= total_w or new_y >= total_h:
        continue

    loc_dic[loc] = {'global_react':[global_new_x,global_new_y,split_h,split_w],'local_react':[new_x,new_y,split_h,split_w]}
```

We sincerely appreciate your careful review and valuable feedback.
